# Generated by Django 2.2 on 2019-06-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OxER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elibrary',
            name='oer',
            field=models.BooleanField(default=True),
        ),
    ]
