# Generated by Django 2.2 on 2019-06-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OxER', '0003_auto_20190602_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='elibrary',
            name='oer',
            field=models.BooleanField(default=True),
        ),
    ]
